import test from 'node:test';
import assert from 'node:assert/strict';
import { access, readFile, readdir, stat } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { Script } from 'node:vm';

const root = join(fileURLToPath(new URL('.', import.meta.url)), '..');

test('service worker app shell contains every runtime module and required asset', async () => {
  const worker = await readFile(join(root, 'service-worker.js'), 'utf8');
  const required = [
    'index.html', 'manifest.webmanifest', 'assets/seafaring-adventure.webp',
    'assets/location-scenes/tapas-locations-atlas.jpg',
    'assets/location-scenes/soup-locations-atlas.jpg',
    'assets/location-scenes/salad-locations-atlas.jpg',
    'assets/location-scenes/main-locations-atlas.jpg',
    'assets/location-scenes/dessert-locations-atlas.jpg',
    'assets/location-scenes/cocktails-locations-atlas.jpg',
    'css/base.css', 'css/layout.css', 'css/components.css', 'css/animations.css',
    'js/app.bundle.js', 'js/app.js', 'js/config.js', 'js/core/audio.js', 'js/core/game-engine.js',
    'js/core/random.js', 'js/core/storage.js', 'js/core/timers.js',
    'js/data/chapters.js', 'js/data/story-events.js', 'js/data/events.js', 'js/data/i18n.js',
    'js/data/ingredients.js', 'js/data/roles.js', 'js/data/tasks.js',
    'js/ui/dialog.js', 'js/ui/game.js', 'js/ui/helpers.js',
    'js/ui/overlays.js', 'js/ui/welcome.js'
  ];
  for (const relative of required) {
    await access(join(root, relative));
    assert.match(worker, new RegExp(relative.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }
});

test('runtime has no remote scripts, fonts, stylesheets, images, or analytics', async () => {
  const files = ['index.html', 'css/base.css', 'css/layout.css', 'css/components.css', 'css/animations.css', 'js/app.js'];
  for (const relative of files) {
    const text = await readFile(join(root, relative), 'utf8');
    assert.doesNotMatch(text, /https?:\/\//i, relative);
    assert.doesNotMatch(text, /google-analytics|gtag|segment|posthog|facebook\.net/i, relative);
  }
  const artwork = await stat(join(root, 'assets/seafaring-adventure.webp'));
  assert.ok(artwork.size > 100_000 && artwork.size < 1_000_000);
});

test('manifest and licence describe the requested offline source-available product', async () => {
  const manifest = JSON.parse(await readFile(join(root, 'manifest.webmanifest'), 'utf8'));
  assert.equal(manifest.name, 'Adventure Dinner: Seafaring Adventure');
  assert.equal(manifest.display, 'standalone');
  assert.equal(manifest.start_url, './');
  const licence = await readFile(join(root, 'LICENSE'), 'utf8');
  assert.match(licence, /Copyright \(c\) 2026 Jonas Lummerzheim/);
  assert.match(licence, /may not[\s\S]*rehost/i);
  assert.match(licence, /not an open-source licence/i);
});

test('entry point uses the generated file-compatible bundle and contains no login or inline application script', async () => {
  const html = await readFile(join(root, 'index.html'), 'utf8');
  assert.ok(Buffer.byteLength(html) < 10_000);
  assert.match(html, /<script\s+defer\s+src="\.\/js\/app\.bundle\.js\?v=1\.4\.0"><\/script>/);
  assert.doesNotMatch(html, /type=["']password["']|login|sign[ -]?in/i);
  assert.equal((html.match(/<script\b/gi) ?? []).length, 1);
});

test('generated bundle is classic-script compatible and up to date', async () => {
  const indexPath = join(root, 'index.html');
  const html = await readFile(indexPath, 'utf8');
  const scriptSource = html.match(/<script\s+defer\s+src="([^"]+)"/)?.[1];
  assert.ok(scriptSource);
  const bundlePath = fileURLToPath(new URL(scriptSource, pathToFileURL(indexPath)));
  await access(bundlePath);
  const bundle = await readFile(join(root, 'js', 'app.bundle.js'), 'utf8');
  assert.match(bundle, /Generated by tools\/build-bundle\.mjs/);
  assert.match(bundle, /function adventureDinnerApplication/);
  assert.doesNotMatch(bundle, /^\s*(?:import|export)\b/m);
  assert.match(bundle, /const APP_VERSION = '1\.4\.0'/);
  assert.doesNotThrow(() => new Script(bundle));
});

test('automatic task skips and busy-crew resumes always trigger a visible handover', async () => {
  const app = await readFile(join(root, 'js', 'app.js'), 'utf8');
  assert.match(app, /previousPlayerId[\s\S]*activePlayer\.id !== previousPlayerId\) showHandover\(\)/);
  assert.match(app, /wasCrewBusy[\s\S]*state\.turn\.phase !== 'crewBusy'\) showHandover\(\)/);
  assert.doesNotMatch(app, /if \(result !== 'chain'\) showHandover\(\)/);
});

test('parchment card choices use a dark high-contrast palette in every state', async () => {
  const css = await readFile(join(root, 'css', 'components.css'), 'utf8');
  assert.match(css, /\.game-card \.choice-button,[\s\S]*?color:\s*#2a2012;[\s\S]*?background:\s*#fff1c9;/);
  assert.match(css, /\.game-card \.choice-button:hover,[\s\S]*?color:\s*#171006;[\s\S]*?background:\s*#fffaf0;/);
  assert.match(css, /\.game-card \.choice-button:focus-visible,[\s\S]*?outline-color:\s*#4f3210;/);
  assert.match(css, /\.game-card button\[disabled\][\s\S]*?color:\s*#5e503c;[\s\S]*?opacity:\s*\.75;/);
});

test('the shared start and eating backdrop keeps the complete island map width visible', async () => {
  const css = await readFile(join(root, 'css', 'components.css'), 'utf8');
  assert.match(css, /\.hero-screen::before[\s\S]*?background-size:\s*cover,\s*100% auto;/);
});

test('the long German completion title has a dedicated responsive layout', async () => {
  const css = await readFile(join(root, 'css', 'components.css'), 'utf8');
  const game = await readFile(join(root, 'js', 'ui', 'game.js'), 'utf8');
  assert.match(game, /class="game-complete-title"/);
  assert.doesNotMatch(game, /gameCompleteTitle[\s\S]{0,80}font-size:/);
  assert.match(css, /\.hero-card \.game-complete-title\s*\{[\s\S]*?max-width:\s*100%;[\s\S]*?overflow-wrap:\s*break-word;/);
});

test('location board uses cinematic scene assets without player circles and the die stays three-dimensional', async () => {
  const css = await readFile(join(root, 'css', 'components.css'), 'utf8');
  const game = await readFile(join(root, 'js', 'ui', 'game.js'), 'utf8');
  const sceneFiles = (await readdir(join(root, 'assets', 'location-scenes'))).sort();
  assert.deepEqual(sceneFiles, [
    'cocktails-locations-atlas.jpg',
    'dessert-locations-atlas.jpg',
    'main-locations-atlas.jpg',
    'salad-locations-atlas.jpg',
    'soup-locations-atlas.jpg',
    'tapas-locations-atlas.jpg'
  ], 'every island is represented by exactly one atlas');
  assert.match(css, /\.station-scene\[data-atlas="true"\][\s\S]*?background-size:\s*cover,\s*200% 300%/);
  assert.match(css, /\.station-caption/);
  assert.match(css, /\.voyage-map/);
  assert.match(css, /\.active-course-heading/);
  assert.match(css, /\.sea-route\[data-state="sailed"\]/);
  assert.doesNotMatch(css, /\.station-person/);
  assert.match(css, /transform-style:\s*preserve-3d/);
  assert.match(css, /\.die-front[\s\S]*?\.die-back[\s\S]*?\.die-right[\s\S]*?\.die-left[\s\S]*?\.die-top[\s\S]*?\.die-bottom/);
  assert.match(game, /LOCATION_SCENES/);
  assert.match(game, /location-scenes\/tapas-locations-atlas\.jpg/);
  assert.match(game, /location-scenes\/soup-locations-atlas\.jpg/);
  assert.equal((game.match(/location-scenes\/[a-z]+-locations-atlas\.jpg/g) ?? []).length, 6,
    'every island uses exactly one six-location atlas');
  assert.doesNotMatch(game, /tapas-(?:harbour|lighthouse|village|market|olive|smugglers)/);
  assert.ok(game.indexOf('class="active-course-heading"') < game.indexOf('class="voyage-map"'), 'the active course heading is rendered above the island map');
  assert.ok(game.indexOf('class="voyage-map"') < game.indexOf('class="station-scene"'), 'the island map is rendered above the current location scene');
  assert.match(game, /t\(engine\.currentChapter\.course, language\)/);
  assert.doesNotMatch(game, /station-person/);
  assert.match(game, /die-cube/);
  assert.match(game, /5:\s*\[1, 3, 5, 7, 9\]/);
  assert.equal((game.match(/renderDieFace\('die-/g) ?? []).length, 6);
});

test('GitHub Pages workflow validates and stages only the static runtime', async () => {
  const workflow = await readFile(join(root, '.github', 'workflows', 'pages.yml'), 'utf8');
  assert.match(workflow, /run: npm run validate/);
  assert.match(workflow, /mkdir -p _site/);
  assert.match(workflow, /cp -r assets css js _site\//);
  assert.match(workflow, /path: _site/);
  assert.doesNotMatch(workflow, /cp -r \. _site|cp -r \* _site/);
});
